name: Test Milestone Due Date

on:
  milestone:
    types: [created, edited]

jobs:
  announce-milestone-due-date:
    runs-on: ubuntu-latest
    if: github.event.milestone.due_on
    steps:
      - run: |
          dueDate=${"${{ github.event.milestone.due_on }}"%T*} 
          if [ $dueDate = $(date '+%F') ]; then
            dueDate=today
          else
            dueDate="on $(date -d $dueDate '+%B %d')"
          fi
          echo ${{ github.event.repository.name }}-planning `${{ github.event.milestone.title }}` $dueDate
