name: Build with Gradle and Stage Release to Artifactory

on:
  workflow_call:
    inputs:
      releaseVersion:
        description: 'Release version like 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
        type: string
      gradleTasks:
        description: 'Additional Gradle tasks. The `build` and `artifactoryPublish` are included.'
        required: false
        type: string
      artifactoryUrl:
        description: 'The Artifactory Server'
        required: false
        type: string
      stagingRepository:
        description: 'The Artifactory Repository to stage artifacts to'
        required: false
        type: string
        default: libs-staging-local
      artifactoryProjectKey:
        description: 'The Artifactory project key'
        required: false
        type: string
      runner:
        description: 'The runner for job'
        required: false
        type: string
        default: ubuntu-latest

    outputs:
      buildName:
        description: 'Artifactory Build Name'
        value: ${{ jobs.staging-to-artifactory-with-gradle.outputs.buildName }}
      buildNumber:
        description: 'Artifactory Build Number'
        value: ${{ jobs.staging-to-artifactory-with-gradle.outputs.buildNumber }}

    secrets:
      GH_ACTIONS_REPO_TOKEN:
        required: true
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true
      DEVELOCITY_ACCESS_KEY:
        required: false
      GPG_PASSPHRASE:
        required: false
      GPG_PRIVATE_KEY:
        required: false

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  WORKFLOWS_REF: v5

jobs:
  staging-to-artifactory-with-gradle:
    runs-on: ${{ inputs.runner }}
    outputs:
      buildName: ${{ steps.build-and-publish.outputs.buildName }}
      buildNumber: ${{ steps.build-and-publish.outputs.buildNumber }}

    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Checkout Common Repo
        uses: actions/checkout@v4
        with:
          repository: spring-io/spring-github-workflows
          path: spring-github-workflows
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - name: Build and Publish
        id: build-and-publish
        timeout-minutes: 30
        uses: ./spring-github-workflows/.github/actions/spring-artifactory-gradle-build
        with:
          releaseVersion: ${{ inputs.releaseVersion }}
          gradleTasks: ${{ inputs.gradleTasks }}
          artifactoryUrl: ${{ inputs.artifactoryUrl }}
          targetRepository: ${{ inputs.stagingRepository }}
          artifactoryProjectKey: ${{ inputs.artifactoryProjectKey }}
          artifactoryUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
          artifactoryPassword: ${{ secrets.ARTIFACTORY_PASSWORD }}
          gpgPrivateKey: ${{ secrets.GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
