name: CI Artifactory SNAPSHOT Build for Gradle

on:
  workflow_call:
    inputs:
      gradleTasks:
        description: 'Additional Gradle tasks. The `build` and `artifactoryPublish` are included.'
        required: false
        type: string
      artifactoryUrl:
        description: 'The Artifactory Server'
        required: false
        type: string
      targetRepository:
        description: 'The Artifactory Repository to upload snapshot artifacts to'
        required: false
        type: string
      artifactoryProjectKey:
        description: 'The Artifactory project key'
        required: false
        type: string
      runner:
        description: 'The runner for job'
        required: false
        type: string
        default: ubuntu-latest

    secrets:
      GRADLE_ENTERPRISE_CACHE_USER:
        required: false
      GRADLE_ENTERPRISE_CACHE_PASSWORD:
        required: false
      GRADLE_ENTERPRISE_SECRET_ACCESS_KEY:
        required: false
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true
      GPG_PASSPHRASE:
        required: false
      GPG_PRIVATE_KEY:
        required: false

env:
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  WORKFLOWS_REF: v3

jobs:
  build-snapshot-with-gradle:
    runs-on: ${{ inputs.runner }}
    name: CI Build SNAPSHOT for ${{ github.ref_name }}
    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Checkout Common Repo
        uses: actions/checkout@v4
        with:
          repository: spring-io/spring-github-workflows
          path: spring-github-workflows
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - name: Build and Publish
        timeout-minutes: 30
        uses: ./spring-github-workflows/.github/actions/spring-artifactory-gradle-build
        with:
          artifactoryUrl: ${{ inputs.artifactoryUrl }}
          targetRepository: ${{ inputs.targetRepository }}
          artifactoryProjectKey: ${{ inputs.artifactoryProjectKey }}

