name: Automatically cherry-pick commit

on:
  workflow_call:
    inputs:
      autoCherryPickToken:
        description: 'The sub-string in the commit message to determine that commit has to be cherry-picked'
        required: false
        default: Auto-cherry-pick to
        type: string

    secrets:
      GH_ACTIONS_REPO_TOKEN:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, inputs.autoCherryPickToken)
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          show-progress: false
          fetch-depth: 0

      - name: Cherry-pick to branches in commit message
        run: |
          git config --global user.name 'Spring Builds'
          git config --global user.email 'builds@springframework.org'
          cherryPickToken=${{ inputs.autoCherryPickToken }}
          commitMessage=${{ github.event.head_commit.message }}
          branches=$(echo '$commitMessage' | grep '$cherryPickToken' | grep -o1 -E "([0-9]+\.[0-9]+\.x)")
          branchCommitMessage=$(echo '$commitMessage' | grep -v '$cherryPickToken')
          for branch in $branches
          do 
            git checkout $branch
            if git cherry-pick ${{ github.sha }}
            then
              echo "::notice title=Commit cherry-picked::${{ github.sha }} to branch `$branch`"
            else
              echo "::error title=Cannot cherry-pick::${{ github.sha }} to branch `$branch`. Manual procedure required"
              exit 1
            fi
            git commit –amend -m $branchCommitMessage  
            git push $branch
          done
