name: Promote Staged GA release from Artifactory to Maven Central

on:
  workflow_call:
    inputs:
      artifactoryProjectKey:
        description: 'The Artifactory project key'
        required: false
        type: string
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string
      targetRepository:
        description: 'The Artifactory Repository to promote the build to'
        required: false
        type: string
        default: libs-release-local
      runner:
        description: 'The runner for job'
        required: false
        type: string
        default: ubuntu-latest

    secrets:
      OSSRH_URL:
        required: false
      OSSRH_S01_TOKEN_USERNAME:
        required: false
      OSSRH_S01_TOKEN_PASSWORD:
        required: false
      OSSRH_STAGING_PROFILE_NAME:
        required: false
      JF_ARTIFACTORY_SPRING:
        required: true

env:
  JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
  OSSRH_URL: ${{ secrets.OSSRH_URL }}
  WORKFLOWS_REF: v3

jobs:
  release-to-central:
    runs-on: ${{ inputs.runner }}
    steps:

      - uses: actions/checkout@v4
        with:
          repository: spring-io/spring-github-workflows
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - uses: jfrog/setup-jfrog-cli@v4

      - name: Promote Build
        run: jfrog rt build-promote ${{ inputs.buildName }} ${{ inputs.buildNumber }} ${{ inputs.targetRepository }} --project=${{ inputs.artifactoryProjectKey }}

      - name: Download Release Files
        if: env.OSSRH_URL
        run: |
          jfrog rt download \
            --spec utils/release-files-spec.json \
            --spec-vars "buildname=${{ inputs.buildName }};buildnumber=${{ inputs.buildNumber }}"

      - uses: spring-io/nexus-sync-action@v0.0.1
        id: nexus
        if: env.OSSRH_URL
        with:
          url: ${{ env.OSSRH_URL }}
          username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
          password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
          staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
          create: true
          upload: true
          generate-checksums: true
          upload-parallel: 10
          close: true
          release: true