name: Distribute Spring Enterprise Release Bundle

# Intended to be used in private repositories for commercial releases where allowed ubuntu22-2-8 GH runner is available

on:
  workflow_call:

    inputs:
      artifactoryUrl:
        description: 'The Artifactory Server'
        required: true
        type: string
      bundleName:
        description: 'The Artifactory Bundle Name'
        required: true
        type: string
      releaseVersion:
        description: 'The Bundle Version (usually project release)'
        required: true
        type: string
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

    secrets:
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true

jobs:
  distribute-spring-enterprise-release-bundle:
    runs-on: ubuntu22-2-8
    steps:

      - run: |
          ARTIFACTORY_CLIENT='curl -s -u "${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }}" -X POST -H "Content-Type: application/json" --fail --show-error --url "${{ inputs.artifactoryUrl }}/lifecycle/api/v2"'
          
          BUNDLE_JSON='{"release_bundle_name": "${{ inputs.bundleName }}", "release_bundle_version": "${{ inputs.releaseVersion }}", "skip_docker_manifest_resolution": true, "source_type": "builds", "source": {"builds": [ {"build_repository": "spring-build-info", "build_name": "${{ inputs.buildName }}", "build_number": "${{ inputs.buildNumber }}"}]}}'
          eval $ARTIFACTORY_CLIENT/release_bundle?project=spring&async=false -H "X-JFrog-Signing-Key-Name: packagesKey" -d '"$BUNDLE_JSON"'

          DISTRIBUTION_JSON='{"auto_create_missing_repositories": "false", "distribution_rules": [{"site_name": "JP-SaaS"}], "modifications": {"mappings": [{"input": "spring-enterprise-maven-prod-local/(.*)", "output": "spring-enterprise/$1"}]}}'
          eval $ARTIFACTORY_CLIENT/distribution/distribute/${{ inputs.bundleName }}/${{ inputs.releaseVersion }}?project=spring -d '"$DISTRIBUTION_JSON"'

