name: Create GH release and Notify Slack

on:
  workflow_call:
    inputs:
      milestone:
        description: 'Milestone title, e.g 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
        type: string

    secrets:
      SPRING_RELEASE_CHAT_WEBHOOK_URL:
        required: false
      GH_ACTIONS_REPO_TOKEN:
        required: true

env:
  MILESTONE: ${{ inputs.milestone }}
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SPRING_MAIN_BANNERMODE: off

jobs:
  finalize-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Changelog Config File
        run: |
          repositoryTeam=$(gh api repos/$GITHUB_REPOSITORY/collaborators --jq 'map(select(.role_name == "admin") | .login) | tostring')
          repositoryTeam=$(sed 's/"//g' <<< ${repositoryTeam:1:-1})
          repositoryVisibility=$(gh repo view --json visibility --jq .[])
          repositoryVisibility=$([[ $repositoryVisibility = 'PUBLIC' ]] && echo 'true' || echo 'false')
          
          echo "changelog.contributors.exclude.names=$repositoryTeam" > changelog.properties
          echo "changelog.issues.generate-links=$repositoryVisibility" >> changelog.properties

      - name: Generate Changelog
        uses: spring-io/github-changelog-generator@v0.0.11
        with:
          milestone: ${{ env.MILESTONE }}
          token: ${{ env.GITHUB_TOKEN }}
          config-file: changelog.properties

      - name: GitHub Release
        run: |
          RELEASE_URL=$(gh release create v${{ env.MILESTONE }} -F changelog.md ${{ (contains(env.MILESTONE, '-M') || contains(env.MILESTONE, '-RC')) && '--prerelease' || '' }})
          echo "::notice title=Release Page::$RELEASE_URL"

      - name: Close Milestone
        run: |
          MILESTONE_ID=$(gh api repos/$GITHUB_REPOSITORY/milestones --jq '.[] | select(.title == env.MILESTONE) | .number')
          if [ $MILESTONE_ID ]; then
            gh api -X PATCH repos/$GITHUB_REPOSITORY/milestones/$MILESTONE_ID -f state='closed' --silent
          fi

      - name: Announce Release in Chat
        uses: julb/action-post-googlechat-message@v1
        if: env.CHAT_WEBHOOK_URL
        with:
          message: "${{ github.event.repository.name }}-announcing `${{ env.MILESTONE }}`"
          gchat_webhook_url: ${{ secrets.SPRING_RELEASE_CHAT_WEBHOOK_URL }}
        env:
          CHAT_WEBHOOK_URL: ${{ secrets.SPRING_RELEASE_CHAT_WEBHOOK_URL }}

#      - name: Announce Release on Slack
#        uses: slackapi/slack-github-action@v1.26.0
#        if: env.SLACK_WEBHOOK_URL
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SPRING_RELEASE_SLACK_WEBHOOK_URL }}
#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
#        with:
#          payload: |
#            {
#              "text": "${{ github.event.repository.name }}-announcing `${{ env.MILESTONE }}`"
#            }