name: Automatically cherry-pick commit

on:
  workflow_call:

    secrets:
      GH_ACTIONS_REPO_TOKEN:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'auto-cherry-pick')
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          show-progress: false

      - name: Cherry-pick to branches in commit message
        run: |
          git config --global user.name 'Spring Builds'
          git config --global user.email 'builds@springframework.org'
          branches=$(echo '${{ github.event.head_commit.message }}' | grep -i auto-cherry-pick | grep -o1 -E "([0-9]+\.[0-9]+\.x)")
          branchCommitMessage=$(echo '${{ github.event.head_commit.message }}' | grep -v -i auto-cherry-pick)
          for branch in $branches
          do 
            git checkout $branch
            if git cherry-pick ${{ github.sha }}
            then
              echo "::notice title=Commit cherry-picked::${{ github.sha }} to branch `$branch`"
            else
              echo "::error title=Cannot cherry-pick::${{ github.sha }} to branch `$branch`. Manual procedure required"
              exit 1
            fi
            git commit –amend -m $branchCommitMessage  
            git push origin $branch
          done
