name: CI Artifactory SNAPSHOT Build for Gradle

on:
  workflow_call:
    inputs:
      gradleTasks:
        description: 'Additional Gradle tasks. The `build` and `artifactoryPublish` are included.'
        required: false
        type: string
      artifactoryUrl:
        description: 'The Artifactory Server'
        required: false
        type: string
        default: https://repo.spring.io
      targetRepository:
        description: 'The Artifactory Repository to upload snapshot artifacts to'
        required: false
        type: string
        default: libs-snapshot-local
      artifactoryProjectKey:
        description: 'The Artifactory project key'
        required: false
        type: string

    secrets:
      GRADLE_ENTERPRISE_CACHE_USER:
        required: false
      GRADLE_ENTERPRISE_CACHE_PASSWORD:
        required: false
      GRADLE_ENTERPRISE_SECRET_ACCESS_KEY:
        required: false
      ARTIFACTORY_USERNAME:
        required: false
      ARTIFACTORY_PASSWORD:
        required: false

env:
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
  ARTIFACTORY_URL: ${{ inputs.artifactoryUrl }}/artifactory
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  ARTIFACTORY_REPOSITORY: ${{ inputs.targetRepository }}
  ARTIFACTORY_BUILD_PROJECT: ${{ inputs.artifactoryProjectKey }}
  ARTIFACTORY_BUILD_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
  ARTIFACTORY_BUILD_NUMBER: ${{ github.run_number }}
  ARTIFACTORY_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  ARTIFACTORY_USER_AGENT_NAME: ${{ runner.name }}
  WORKFLOWS_REF: main

jobs:
  build-snapshot-with-gradle:
    runs-on: ubuntu-latest
    name: CI Build SNAPSHOT for ${{ github.ref_name }}
    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Checkout Common Repo
        uses: actions/checkout@v4
        with:
          repository: spring-io/spring-github-workflows
          path: build
          show-progress: false
          ref: ${{ env.WORKFLOWS_REF }}

      - name: Set up Gradle
        uses: spring-io/spring-gradle-build-action@v2

      - name: Build and Publish
        run: |
          agentVersion=$(./run.sh --version)
          echo ARTIFACTORY_USER_AGENT_VERSION=$agentVersion >> $GITHUB_ENV
          cp build/utils/*.gradle $HOME/.gradle/init.d
          gradle clean build ${{ inputs.gradleTasks }} artifactoryPublish

