name: "Sync Code"

on:
  push: # run if we update the workflow
  workflow_dispatch:
  schedule:
    - cron: '39 13 * * 4'
permissions:
  contents: write
jobs:
  sync:
    name: Sync (${{ matrix.repo }})
    # Runner size impacts CodeQL analysis time. To learn more, please see:
    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
    #   - https://gh.io/supported-runners-and-hardware-resources
    #   - https://gh.io/using-larger-runners (GitHub.com only)
    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        include:
          - repository: spring-io/spring-github-workflows
            branch: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: '${{ matrix.repository }}'
          branch: '${{ matrix.branch }}'

      - name: add remote and push
        run: |
          export REMOTE_NAME=remote-to-sync
          export REMOTE_BRANCH='${{ matrix.repository }}/${{ matrix.branch }}'
          git remote add "$REMOTE_NAME" '${{ github.event.repository.ssh_url }}'
          git checkout -b "$REMOTE_BRANCH"
          git push "$REMOTE_NAME" "$REMOTE_BRANCH"
