name: "Sync Code"

on:
  push: # run if we update the workflow
  workflow_dispatch:
  schedule:
    - cron: '39 13 * * 4'
permissions:
  contents: write
jobs:
  sync:
    name: Sync (${{ matrix.repo }})
    # Runner size impacts CodeQL analysis time. To learn more, please see:
    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
    #   - https://gh.io/supported-runners-and-hardware-resources
    #   - https://gh.io/using-larger-runners (GitHub.com only)
    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        include:
          - repository: spring-io/spring-github-workflows
            branch: main
    steps:
      - name: Checkout repository # setup credentials for push
        uses: actions/checkout@v4

      - name: Sync
        run: |
          git remote add push https://${{ secrets.SPRING_CODEQL_PUSH_CLASSIC }}@github.com/rwinch/spring-codeql
          git remote add external https://github.com/spring-io/spring-github-workflows
          git fetch external main
          git checkout --detach FETCH_HEAD
          git push origin HEAD:refs/heads/spring-io/spring-github-workflows/main
